spring:
  application:
    name: restful-api
  datasource:
    url: jdbc:mysql://localhost:3306/spring
    username: root
    password: 123456
    platform: mysql
#    schema:
#      - classpath:sql/schema.sql
#    data:
#      - classpath:sql/books.sql
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  data:
    rest:
      base-path: /v2
      default-page-size: 10


server:
  servlet:
    context-path: /api

logging:
  level:
    org:
      springframework:
        security: DEBUG

security:
  oauth2:
    client:
#      客户端 id
      client-id: resful
#      客户端密钥
      client-secret: restfulSecret
#      范围
      scope: all
#      有效时间
      access-token-validity-seconds: 6000
#      刷新时间
      refresh-token-validity-seconds: 6000
#      token 名字
      token-name: oauth_token
#      授权类型 密码模式
      grant-type: password
#      回调地址
#      registered-redirect-uri: http://example.com

